runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:/M/ro4AI2YU5NXU36RIcKjRc4miG6cgm1CWS2c++/z8=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie